#!/bin/bash

NPM_BIN="./node_modules/.bin"

git_cached_files=$(git diff --cached --name-only --diff-filter=ACMR -- '*.ts' | xargs echo)
if [ "$git_cached_files" ]; then
    echo -ne "  \033[0;33m✘$(tput init) TSLint\r"
    $NPM_BIN/tslint $git_cached_files && echo -ne "  \033[0;32m✓$(tput init) TSLint\n" || exit 1
fi
